sudo: required
dist: trusty
install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y dpkg g++-6 git make python3 python3-numpy python3-dev libgoogle-glog-dev
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 1
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/v/verilator/verilator_3.916-1build1_amd64.deb
    - sudo dpkg -i verilator_3.916-1build1_amd64.deb
    - git submodule update --init --recursive
script:
    - make -C sim/UmiModel
    - make -C nicotb/lib/cpp
    - make -C sim_verilator top_sc_all
branches:
    only:
        - master
