// Copyright 2018 Yu Sheng Lin

// This file is part of MIMORI.

// MIMORI is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// MIMORI is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with MIMORI.  If not, see <http://www.gnu.org/licenses/>.


// Generated by Jinja2
function [4:0] RemapCacheLowRotate5;
	input [4:0] i_lower;
	input [7:0] i_flags;
	logic [4:0] l [8];
	l[0] = i_lower;
	l[1] = i_flags[0] ? {l[0][0:0], l[0][4:1]} : l[0];
	l[2] = i_flags[1] ? {l[1][1:0], l[1][4:2]} : l[1];
	l[3] = i_flags[2] ? {l[2][3:3], l[2][4:4], l[2][2:0]} : l[2];
	l[4] = i_flags[3] ? {l[3][2:2], l[3][4:3], l[3][1:0]} : l[3];
	l[5] = i_flags[4] ? {l[4][3:2], l[4][4:4], l[4][1:0]} : l[4];
	l[6] = i_flags[5] ? {l[5][0:0], l[5][4:1]} : l[5];
	l[7] = i_flags[6] ? {l[6][1:0], l[6][4:2]} : l[6];
	RemapCacheLowRotate5 = i_flags[7] ? {l[7][3:0], l[7][4:4]} : l[7];
endfunction
