// Copyright 2018 Yu Sheng Lin

// This file is part of MIMORI.

// MIMORI is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// MIMORI is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with MIMORI.  If not, see <http://www.gnu.org/licenses/>.
{% macro Sliced(lg_n, used, shamt, i) -%}
	{{'{'}}
	{%- if lg_n == used -%}
		l[{{i}}][{{shamt-1}}:0], l[{{i}}][{{lg_n-1}}:{{shamt}}]
	{%- else -%}
		l[{{i}}][{{lg_n-used+shamt-1}}:{{lg_n-used}}], l[{{i}}][{{lg_n-1}}:{{lg_n-used+shamt}}], l[{{i}}][{{lg_n-used-1}}:0]
	{%- endif -%}{{'}'}}
{%- endmacro %}

// Generated by Jinja2
function [{{lg_n-1}}:0] RemapCacheLowRotate{{lg_n}};
	input [{{lg_n-1}}:0] i_lower;
	input [{{sw_layer-1}}:0] i_flags;
	logic [{{lg_n-1}}:0] l [{{sw_layer}}];
	l[0] = i_lower;
	{%- for i in range(sw_layer) %}
	{% if loop.last -%}
		RemapCacheLowRotate{{lg_n}}
	{%- else -%}
		l[{{i+1}}]
	{%- endif %} = i_flags[{{i}}] ? {{ Sliced(lg_n, cfg[i][0], cfg[i][1], i) }} : l[{{i}}];
	{%- endfor %}
endfunction

