// Copyright 2018 Yu Sheng Lin

// This file is part of MIMORI.

// MIMORI is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// MIMORI is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with MIMORI.  If not, see <http://www.gnu.org/licenses/>.

module RemapCacheSwapUnit{{lg_n}}#(
	parameter BW=32
)(
	input [BW-1:0] i_data [{{n}}],
	input [{{sw_layer-1}}:0] i_flags,
	output logic [BW-1:0] o_data [{{n}}]
);

// Generated by Jinja2
logic [BW-1:0] l [{{sw_layer+1}}][{{n}}];

always_comb begin
	l[0] = i_data;
	{%- for i in range(sw_layer) %}
	if (i_flags[{{i}}]) begin
		{%- for j in range(n) %}
		l[{{i+1}}][{{j}}]=l[{{i}}][{{sw[i,j]}}];
	{%- endfor %}
	end else begin
		l[{{i+1}}] = l[{{i}}];
	end
	{%- endfor %}
	o_data = l[{{sw_layer}}];
end

endmodule

